### ISSUE TITLE
Utility Viewer - GIS Locator returning inactive features

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#184] opened 2015-10-12 18:00 UTC
Please check the Locator, as it is returning IDs for features that are not active.  For example, a search for hydrants starting with 02289\* returns 022896, which has a status of removed.

![capture](https://cloud.githubusercontent.com/assets/7118831/10434773/8817ffc4-70e9-11e5-83b1-1cd6a12f84bb.JPG)

**Comment by JMurk** [comment] 2016-03-02 16:23
The list includes the values, but does not zoom to the location since the feature is not actually displayed on the map/included in the map service layer.

**Comment by taojun545** [comment] 2016-03-15 17:55
Fixed on dev.
When searching hydrants, it will return all active results with FEAT_STATUS='ACT'. (Such as "02392%", 023922-R and 023929 will not be shown)

For other layers, it may have same issue. We need to check what is the status column in each table.

**Comment by JMurk** [comment] 2016-03-16 14:12
We need to query for this list through the map service rather than the database directly in order to include the definition queries that are specific to each layer.

**Comment by taojun545** [comment] 2016-03-18 19:28
Updated on prod, but it only fixed Hydrants search.

I will re-do the GIS Locator function to directly query MapService instead of Database.

**Comment by taojun545** [comment] 2016-03-22 16:57
New GIS Locator function updated on dev.

The new GIS Locator will query MapServer instead of database. It will always return active features from MapServer. If any query need to be changed, the only file need to be updated is "GisLocatorConfig/LocatorConfig.xml".

**Comment by JMurk** [comment] 2016-03-23 13:46
Please update for CSR layers.

**Comment by JMurk** [comment] 2016-04-04 13:32
I have updated the map services for CSRs in both dev and prod to include the SRX and SRY fields.

**Comment by taojun545** [comment] 2016-04-04 17:34
Update on dev.

The "GisLocatorConfig/LocatorConfig.xml" may need double check, I found one issue for:
    <layer>
      <servicename>Leaks</servicename>
      <layername>Historical Leaks</layername>
      <fieldname>Leak ID</fieldname>
      <searchname>Leak_Object_ID</searchname>
    </layer>

Most of the Leak Layers have "Leak_Object_ID", but "Historical Leaks" doesn't. We need to change.

**Comment by alanfoster99** [comment] 2016-04-04 17:54
The Leak_Object_ID is generated automatically, and is used as a unique identifier.  I'm not sure we need to add it to "Historical Leaks" as they will never be changed.

**Comment by JMurk** [comment] 2016-04-04 18:03
For Historical Leaks, use Leak_Name

**Comment by JMurk** [comment] 2016-04-04 19:01
Looks good on dev, ready for push to prod.

**Comment by taojun545** [comment] 2016-04-04 19:59
Updated on prod.

**Comment by JMurk** [comment] 2016-04-13 12:04
Confirmed complete.

**Closed as completed by JMurk** 2016-04-13 12:04 UTC
Labels: moderate priority, bug, ready for prod
